//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectParduotuve.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITEntities1 : DbContext
    {
        public ITEntities1()
            : base("name=ITEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Darbuotojas> Darbuotojas { get; set; }
        public virtual DbSet<Darbuotojo_menesio_ataskaita> Darbuotojo_menesio_ataskaita { get; set; }
        public virtual DbSet<Kortele> Kortele { get; set; }
        public virtual DbSet<Menesio_prognoze> Menesio_prognoze { get; set; }
        public virtual DbSet<Prisijungimas> Prisijungimas { get; set; }
        public virtual DbSet<Produktas> Produktas { get; set; }
        public virtual DbSet<Produkto_specifikacija> Produkto_specifikacija { get; set; }
        public virtual DbSet<Prognazuojama_preke> Prognazuojama_preke { get; set; }
        public virtual DbSet<Uzsakymas> Uzsakymas { get; set; }
        public virtual DbSet<Uzsakomos_prekes> Uzsakomos_prekes { get; set; }
        public virtual DbSet<Vieta> Vieta { get; set; }

        public System.Data.Entity.DbSet<ProjectParduotuve.Models.ProductSpec> ProductSpecs { get; set; }

        public System.Data.Entity.DbSet<ProjectParduotuve.Models.BusenaEnum> BusenaEnums { get; set; }

        public System.Data.Entity.DbSet<ProjectParduotuve.Models.Card> Cards { get; set; }

        public System.Data.Entity.DbSet<ProjectParduotuve.Models.DarbuotojoMenesioAtaskaita> DarbuotojoMenesioAtaskaitas { get; set; }

        public System.Data.Entity.DbSet<ProjectParduotuve.Models.MenesioProognoze> MenesioProognozes { get; set; }

        public System.Data.Entity.DbSet<ProjectParduotuve.Models.Product> Products { get; set; }

        public System.Data.Entity.DbSet<ProjectParduotuve.Models.ProognozuojamaPreke> ProognozuojamaPrekes { get; set; }

        public System.Data.Entity.DbSet<ProjectParduotuve.Models.RightsType> RightsTypes { get; set; }

        public System.Data.Entity.DbSet<ProjectParduotuve.Models.UzsakomosPrekes> UzsakomosPrekes { get; set; }

        public System.Data.Entity.DbSet<ProjectParduotuve.Models.Worker> Workers { get; set; }
    }
}
