//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectParduotuve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Darbuotoja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Darbuotoja()
        {
            this.Darbuotojo_menesio_ataskaita = new HashSet<Darbuotojo_menesio_ataskaita>();
            this.Uzsakymas = new HashSet<Uzsakyma>();
        }
    
        public int id_Darbuotojas { get; set; }
        public string Vardas { get; set; }
        public string Pavarde { get; set; }
        public string El_pastas { get; set; }
        public string Telefonas { get; set; }
        public Nullable<System.DateTime> Dirba_nuo { get; set; }
        public Nullable<System.DateTime> Dirba_iki { get; set; }
        public bool Aktyvus { get; set; }
        public string Pareigos { get; set; }
        public int fk_id_Prisijungimas { get; set; }
        public int fk_id_Vieta { get; set; }
    
        public virtual Prisijungima Prisijungima { get; set; }
        public virtual Vieta Vieta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Darbuotojo_menesio_ataskaita> Darbuotojo_menesio_ataskaita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzsakyma> Uzsakymas { get; set; }
    }
}
