//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectParduotuve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Darbuotojo_menesio_ataskaita
    {
        public int id_Darbuotojo_menesio_ataskaita { get; set; }
        public int Metai { get; set; }
        public int Menuo { get; set; }
        public Nullable<double> Dirba_nuo_h { get; set; }
        public Nullable<double> Dirba_iki_h { get; set; }
        public string Darbo_dienos { get; set; }
        public double Atlyginimas { get; set; }
        public double Pelnas { get; set; }
        public string Pareigos { get; set; }
        public Nullable<int> fk_id_Vieta { get; set; }
        public Nullable<int> fk_id_Darbuotojas { get; set; }
    
        public virtual Darbuotojas Darbuotojas { get; set; }
        public virtual Vieta Vieta { get; set; }
    }
}
