//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectParduotuve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kortele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kortele()
        {
            this.Uzsakymas = new HashSet<Uzsakymas>();
        }
    
        public int id_Kortele { get; set; }
        public string Vardas { get; set; }
        public string Pavarde { get; set; }
        public string El_pastas { get; set; }
        public string Telefonas { get; set; }
        public System.DateTime Galioja_iki { get; set; }
        public System.DateTime Galioja_nuo { get; set; }
        public bool Aktyvus { get; set; }
        public int fk_id_Prisijungimas { get; set; }
    
        public virtual Prisijungimas Prisijungimas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzsakymas> Uzsakymas { get; set; }
    }
}
