//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectParduotuve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prisijungimas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prisijungimas()
        {
            this.Darbuotojas = new HashSet<Darbuotojas>();
            this.Kortele = new HashSet<Kortele>();
        }
    
        public int id_Prisijungimas { get; set; }
        public string Vardas { get; set; }
        public string Slaptazodis { get; set; }
        public string Teises { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Darbuotojas> Darbuotojas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kortele> Kortele { get; set; }
    }
}
