//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectParduotuve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkto_specifikacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkto_specifikacija()
        {
            this.Produktas = new HashSet<Produkta>();
            this.Prognazuojama_preke = new HashSet<Prognazuojama_preke>();
        }
    
        public int id_Produkto_specifikacija { get; set; }
        public string Pavadinimas { get; set; }
        public double Svoris { get; set; }
        public double Kaina { get; set; }
        public Nullable<double> Nuolaida { get; set; }
        public double Kiekis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkta> Produktas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prognazuojama_preke> Prognazuojama_preke { get; set; }
    }
}
