//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectParduotuve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkta
    {
        public int id_Produktas { get; set; }
        public Nullable<System.DateTime> Pagaminimo_data { get; set; }
        public Nullable<System.DateTime> Pardavimo_data { get; set; }
        public Nullable<System.DateTime> Galiojimo_data { get; set; }
        public double Kiekis { get; set; }
        public string Busena { get; set; }
        public Nullable<int> fk_id_Vieta { get; set; }
        public int fk_id_Uzsakomos_prekes { get; set; }
        public int fk_id_Produkto_specifikacija { get; set; }
    
        public virtual Vieta Vieta { get; set; }
        public virtual Uzsakomos_prekes Uzsakomos_prekes { get; set; }
        public virtual Produkto_specifikacija Produkto_specifikacija { get; set; }
    }
}
