//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectParduotuve.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITEntities : DbContext
    {
        public ITEntities()
            : base("name=ITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Darbuotoja> Darbuotojas { get; set; }
        public virtual DbSet<Darbuotojo_menesio_ataskaita> Darbuotojo_menesio_ataskaita { get; set; }
        public virtual DbSet<Kortele> Korteles { get; set; }
        public virtual DbSet<Menesio_prognoze> Menesio_prognoze { get; set; }
        public virtual DbSet<Prisijungima> Prisijungimas { get; set; }
        public virtual DbSet<Produkta> Produktas { get; set; }
        public virtual DbSet<Produkto_specifikacija> Produkto_specifikacija { get; set; }
        public virtual DbSet<Prognazuojama_preke> Prognazuojama_preke { get; set; }
        public virtual DbSet<Uzsakomos_prekes> Uzsakomos_prekes { get; set; }
        public virtual DbSet<Uzsakyma> Uzsakymas { get; set; }
        public virtual DbSet<Vieta> Vietas { get; set; }
    }
}
