//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectParduotuve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzsakymas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzsakymas()
        {
            this.Uzsakomos_prekes = new HashSet<Uzsakomos_prekes>();
        }
    
        public int id_Uzsakymas { get; set; }
        public System.DateTime Data { get; set; }
        public int fk_id_Vieta { get; set; }
        public int fk_id_Darbuotojas { get; set; }
        public int fk_id_Kortele { get; set; }
    
        public virtual Darbuotojas Darbuotojas { get; set; }
        public virtual Kortele Kortele { get; set; }
        public virtual Vieta Vieta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzsakomos_prekes> Uzsakomos_prekes { get; set; }
    }
}
