//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectParduotuve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzsakomos_prekes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzsakomos_prekes()
        {
            this.Produktas = new HashSet<Produkta>();
        }
    
        public int id_Uzsakomos_prekes { get; set; }
        public double Kiekis { get; set; }
        public Nullable<bool> Patvirtintas { get; set; }
        public Nullable<bool> Pakestas { get; set; }
        public double Kaina { get; set; }
        public Nullable<double> Nuolaida { get; set; }
        public int fk_id_Uzsakymas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkta> Produktas { get; set; }
        public virtual Uzsakyma Uzsakyma { get; set; }
    }
}
