//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectParduotuve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vieta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vieta()
        {
            this.Darbuotojas = new HashSet<Darbuotojas>();
            this.Darbuotojo_menesio_ataskaita = new HashSet<Darbuotojo_menesio_ataskaita>();
            this.Menesio_prognoze = new HashSet<Menesio_prognoze>();
            this.Produktas = new HashSet<Produktas>();
            this.Uzsakymas = new HashSet<Uzsakymas>();
        }
    
        public int id_Vieta { get; set; }
        public string Pavadinimas { get; set; }
        public string Adresas { get; set; }
        public string Paskirtis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Darbuotojas> Darbuotojas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Darbuotojo_menesio_ataskaita> Darbuotojo_menesio_ataskaita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menesio_prognoze> Menesio_prognoze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produktas> Produktas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzsakymas> Uzsakymas { get; set; }
    }
}
